export type Dimension = 'amorcage' | 'peur' | 'personnalisation' | 'autorite' | 'tentation';
export interface Question { id: number; dimension: Dimension; text: string; answers: [string, string, string, string]; }

export const QUESTIONS: Question[] = [
  { id: 1, dimension: 'amorcage', text: "Vous passez devant une vitrine redécorée avec un éclairage chaud. Vous ressentez une envie d'entrer que vous n'aviez pas la veille.", answers: ["J'entre, l'ambiance m'a donné une impulsion que je n'avais pas anticipée.", "Je remarque le changement mais ça ne suffit pas à me faire entrer.", "Je me demande pourquoi cette mise en scène a été changée avant d'agir.", "L'éclairage ne m'influence pas, je continue mon chemin."] },
  { id: 2, dimension: 'amorcage', text: "Un collègue utilise son ton habituel mais vous demande d'accéder à un dossier confidentiel pour « lui rendre service rapidement ».", answers: ["Cette familiarité de ton me met en confiance, je l'aide sans poser de question.", "Le ton me semble familier mais je lui demande pourquoi il a besoin de ça maintenant.", "Je trouve la demande inhabituelle malgré le ton familier et je la questionne.", "Je ne me fie jamais au ton pour juger de la légitimité d'une demande."] },
  { id: 3, dimension: 'amorcage', text: "Un animateur projette une photo évocatrice et raconte l'histoire d'un employé fictif « tombé dans le piège » avec un ton inhabituellement dramatique.", answers: ["Le récit me touche profondément et je retiens scrupuleusement chaque conseil donné après.", "Le récit m'interpelle mais je garde mon esprit critique sur les conseils proposés.", "Une mise en scène aussi dramatique pour une formation interne me semble exagérée.", "Je ne suis pas réceptif à ce genre de récit, je retiens seulement les faits."] },
  { id: 4, dimension: 'amorcage', text: "Vous lisez un article captivant en ligne. Une fenêtre parfaitement intégrée propose de « continuer la lecture en mode premium » via un clic.", answers: ["Pris dans ma lecture, je clique presque par réflexe pour ne pas perdre le fil.", "Je termine ma lecture actuelle avant d'envisager de cliquer sur quoi que ce soit.", "Une fenêtre qui s'intègre aussi bien visuellement m'alerte plutôt qu'elle ne m'attire.", "Je ferme systématiquement ce type de fenêtre sans la lire."] },
  { id: 5, dimension: 'peur', text: "Votre badge d'accès refuse de fonctionner. Un collègue dit en blague : « Ça sent le grand ménage des contrats… »", answers: ["Cette simple remarque me met sur les nerfs pour le reste de la journée.", "Je suis un peu secoué mais je vais directement demander à l'accueil ce qui se passe.", "Je prends la remarque pour ce qu'elle est, une blague, et je n'y pense plus.", "Ce genre de rumeur ne m'affecte jamais, je continue ma journée normalement."] },
  { id: 6, dimension: 'peur', text: "Votre manager vous envoie : « Il faut qu'on parle de ton dernier dossier. Passe me voir dès que possible. » Sans autre détail.", answers: ["Je me sens immédiatement mal et j'imagine le pire jusqu'à ce qu'on se parle.", "Je suis inquiet mais je continue ma tâche en cours avant d'y aller.", "Le message est bref mais ça ne veut rien dire en soi, j'irai à un moment calme.", "Je ne m'inquiète pas pour un message aussi vague, j'irai quand j'aurai le temps."] },
  { id: 7, dimension: 'peur', text: "Pendant un contrôle qualité, votre supérieur feuillette votre dossier en silence, le visage fermé, avant de dire « On verra ça plus tard. »", answers: ["Le silence et son expression m'angoissent, je repasse tout mon dossier dans ma tête.", "Je suis un peu inquiet mais j'attends d'avoir un retour concret avant de réagir.", "Je ne tire pas de conclusion d'une expression de visage ou d'un silence.", "Ce genre de réaction ne m'inquiète pas, je connais la qualité de mon travail."] },
  { id: 8, dimension: 'peur', text: "Un email vous informe que votre rapport « présente des incohérences nécessitant une vérification via le portail joint », sans préciser lesquelles.", answers: ["Je panique à l'idée d'avoir mal fait les choses et je clique tout de suite pour vérifier.", "Je suis inquiet mais je contacte directement le service concerné pour en savoir plus.", "Je relis mon dossier original avant de réagir à l'email.", "Sans détail précis sur l'erreur, je ne me sens pas concerné."] },
  { id: 9, dimension: 'personnalisation', text: "Lors d'un pot de départ, la cagnotte circule et tout le monde met la même somme sans discussion préalable.", answers: ["Je donne le même montant que les autres sans poser de question, ça doit être la norme.", "Je donne un montant mais je demande discrètement si c'est le montant habituel.", "Je donne ce que je veux, peu importe ce que les autres ont mis.", "Le comportement du groupe ne m'influence jamais sur ce type de décision personnelle."] },
  { id: 10, dimension: 'personnalisation', text: "Une nouvelle procédure de sécurité est annoncée en réunion. Les explications sont confuses mais vos collègues hochent la tête et notent sans poser de question.", answers: ["Je fais comme eux, s'ils ont l'air de comprendre c'est que ça doit être clair.", "Je note aussi mais je prévois de demander des précisions après la réunion.", "Je pose ma question en réunion, peu importe que les autres semblent comprendre.", "Le comportement des autres ne change rien à mon besoin de clarté personnelle."] },
  { id: 11, dimension: 'personnalisation', text: "Vous expliquez une méthode à un nouveau collaborateur qui vous regarde froidement et fronce légèrement les sourcils sans rien dire.", answers: ["Sa réaction me déstabilise et j'ajuste immédiatement ma façon d'expliquer.", "Je remarque sa réaction mais je termine mon explication comme prévu.", "Son expression ne me dit rien de précis, je continue sans m'en soucier.", "Je lui demande directement ce qui ne lui convient pas plutôt que de deviner."] },
  { id: 12, dimension: 'personnalisation', text: "Un email collectif de la direction demande une action rapide, précisant que « l'ensemble des collaborateurs concernés ont déjà répondu présents ».", answers: ["L'idée que tout le monde a déjà répondu m'incite à faire de même sans attendre.", "Je réponds mais je vérifie d'abord auprès d'un collègue si c'est bien le cas.", "Cette affirmation ne change rien à ma façon de traiter la demande.", "Ce genre de précision me rend justement plus méfiant sur la demande."] },
  { id: 13, dimension: 'autorite', text: "Votre médecin prescrit un traitement sans explication et coupe court à vos questions : « Faites-moi confiance, c'est mon métier. »", answers: ["Je respecte sa position et je suis le traitement sans insister sur mes questions.", "Je suis le traitement mais je cherche des informations par moi-même ensuite.", "J'insiste poliment pour avoir au moins une explication minimale.", "Je consulte un autre avis médical avant de commencer un traitement non expliqué."] },
  { id: 14, dimension: 'autorite', text: "Un jeune collègue critique une procédure. Votre supérieur répond : « Avec l'expérience, on comprend — pour l'instant, suivez-les. »", answers: ["Cette réponse me semble juste, mieux vaut se conformer en attendant de comprendre.", "Je me conforme tout en gardant mes questions pour plus tard.", "Je pense que la critique méritait une vraie réponse, pas juste un appel à l'ancienneté.", "Je soutiendrais plutôt le collègue qui a posé la question."] },
  { id: 15, dimension: 'autorite', text: "Un formateur affirme : « Il y a deux types de personnes : celles qui suivent les consignes, et celles qui finissent par causer un incident. »", answers: ["Je veux clairement être dans la première catégorie, donc je suis les consignes sans les questionner.", "Le message me motive à être vigilant, mais je garde un regard critique sur les consignes elles-mêmes.", "Cette façon de diviser les gens en deux catégories me semble trop simpliste.", "Ce type de discours culpabilisant ne m'influence pas dans mes décisions."] },
  { id: 16, dimension: 'autorite', text: "Un email de la direction : « Mieux vaut suivre les décisions prises en haut lieu sans chercher à tout comprendre — cliquez ici pour confirmer votre adhésion. »", answers: ["Cette vision me semble réaliste, je clique pour confirmer sans chercher plus de détails.", "Je clique mais je demande ensuite des explications sur cette nouvelle politique.", "Je trouve cet argument insuffisant pour justifier d'agir sans comprendre.", "Je vérifie l'authenticité de l'email avant de cliquer sur quoi que ce soit."] },
  { id: 17, dimension: 'tentation', text: "Au marché, un vendeur propose : « Si vous achetez 3 articles au lieu d'1, je vous fais un prix qui vaut vraiment le coup — c'est aujourd'hui seulement. »", answers: ["La perspective de l'économie me motive à acheter plus que prévu.", "Je suis intéressé mais je calcule si j'ai vraiment besoin des articles en plus.", "Une offre limitée au jour même ne m'influence pas particulièrement.", "Je n'achète que ce que j'étais venu chercher, indépendamment du prix."] },
  { id: 18, dimension: 'tentation', text: "Un ami propose un investissement avec un retour sous 3 mois, contre un placement classique en plusieurs années pour un gain équivalent.", answers: ["Le gain plus rapide me semble nettement préférable, je suis tenté d'accepter vite.", "Je suis tenté mais je demande un temps de réflexion avant de m'engager.", "La rapidité du gain ne me convainc pas sans plus de garanties.", "Je préfère systématiquement la sécurité d'un placement classique, même plus lent."] },
  { id: 19, dimension: 'tentation', text: "Lors d'un événement, on vous propose d'accéder à une zone VIP sans badge en suivant quelqu'un qui connaît un accès secondaire.", answers: ["L'occasion est trop tentante, je suis la personne sans trop réfléchir.", "Je suis tenté mais je me retiens en pensant aux conséquences possibles.", "Ce type de contournement ne m'intéresse pas, même si l'occasion se présente.", "Je refuse et je signale la situation par principe."] },
  { id: 20, dimension: 'tentation', text: "Un email propose des points de fidélité en partageant vos coordonnées sur un site partenaire, avec un compteur affichant une offre qui expire dans 10 minutes.", answers: ["Le gain rapide et le compte à rebours me poussent à agir sans plus réfléchir.", "Je suis attiré par le gain mais je prends le temps de vérifier le site partenaire.", "Un compte à rebours aussi court me semble être une technique de pression.", "Je ne suis pas motivé par ce type de gain mineur."] },
];
